name: build test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "build.sh"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build AikoR deb
        run: |
          ./build.sh

      - name: upload AikoR deb
        uses: actions/upload-artifact@v2
        with:
          name: AikoR
          path: AikoR.deb

