name: build test
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "build.sh"
      - "update.sh"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2.4.0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get project dependencies
        run: |
          cd AikoR
          go mod download

      - name: Build AikoR
        run: |
          cd AikoR
          go build -v -o AikoR-linux-64/etc/AikoR -trimpath -ldflags "-s -w -buildid=" ./AikoR

      - name: Build DEB
        run: |
          chmod +x build.sh
          ./build.sh
      
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: AikoR-linux-64
          path: ./AikoR-linux-64/*

